default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: r51wr_development

test:
  <<: *default
  database: r51wr_test

production:
  <<: *default
  database: r51wr_production
